<?php


class LTUServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function boot()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
