<?php

namespace Gregdmat\LaravelTestUtilities;

class LTUServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function boot()
    {
        $this->publishes([
            __DIR__ . 'config/dataCases.php' => config_path('dataCases.php')
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
