<?php

namespace Gregdmat\LaravelTestUtilities;

use Gregdmat\LaravelTestUtilities\src\Console\LTUInstallerCommand;

class LTUServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                LTUInstallerCommand::class
            ]);
        }
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
