<?php

namespace Gregdmat\LaravelTestUtilities;

use Gregdmat\LaravelTestUtilities\Console\LTUInstaller;
use Gregdmat\LaravelTestUtilities\Mocker\ApiMocker;

class LTUServiceProvider extends \Illuminate\Support\ServiceProvider
{

    public function boot()
    {
        ApiMocker::setUp();
        $this->bootRoutes();
        $this->bootCommands();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function bootRoutes()
    {
        include __DIR__ . '/routes/api.php';
    }

    public function bootCommands()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                LTUInstaller::class
            ]);
        }
    }
}
